[project]
name = "Decentralized-Autonomous-Organization-for-Scientific-Research-Funding"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.treasury]
path = "contracts/treasury.clar"
epoch = "latest"

[contracts.delegation]
path = "contracts/delegation.clar"
epoch = "latest"

[contracts.governance]
path = "contracts/governance.clar"
epoch = "latest"

[contracts.proposal]
path = "contracts/proposal.clar"
epoch = "latest"

[contracts.milestone]
path = "contracts/milestone.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
